### ISSUE TITLE
Internet Explorer infinite loop

### ISSUE THREAD

**Issue by karesztrk** [soywod/react-pin-field#19] opened 2020-06-18 10:36 UTC
Hey. I've just started to use this awesome component. But i noticed a bug which only occurs in Internet Explorer.
If the user types the input very fast then the cursor gets swapping between the inputs. Causing the whole browser to shut down (CPU intensive process probably in the background).

Is it a know issue?

**Comment by soywod** [comment] 2020-06-18 11:26
Not at all, and to be honest I didn't test on Internet Explorer. Which version did you use? Does this strange (but funny) bug occurs on Edge?

**Comment by karesztrk** [comment] 2020-06-18 11:47
Its IE11. I also created a screencast about this behavior @ https://drive.google.com/file/d/1rxlqt9F-IPMBTnuaStv5BASr9R8O6UEX/view?usp=sharing

**Comment by soywod** [comment] 2020-06-18 11:59
I will try to reproduce first then investigate. Thank you for your feedback :)

**Comment by MatheusRyuki** [comment] 2020-06-22 12:43
Just an addendum to the problem, despite official Microsoft support ending in 2015, the company itself no longer recommends using it. I believe that support for Internet Explorer should not be considered.

Sources:
https://blog.archive.org/2020/05/01/farewell-to-ie11/
https://techcommunity.microsoft.com/t5/windows-it-pro-blog/the-perils-of-using-internet-explorer-as-your-default-browser/ba-p/331732#

**Comment by karesztrk** [comment] 2020-06-22 12:46
@MatheusRyuki Thanks it was helpful 😄

**Comment by karesztrk** [comment] 2020-06-22 12:47
> 
> 
> Just an addendum to the problem, despite official Microsoft support ending in 2015, the company itself no longer recommends using it. I believe that support for Internet Explorer should not be considered.
> 
> Sources:
> https://blog.archive.org/2020/05/01/farewell-to-ie11/
> https://techcommunity.microsoft.com/t5/windows-it-pro-blog/the-perils-of-using-internet-explorer-as-your-default-browser/ba-p/331732#

@MatheusRyuki Thanks. I'm aware of it. Unfortunately most our users are not....So... 😄

**Comment by soywod** [comment] 2021-03-14 22:40
I just publish the `v1.1.0`. I improved the behaviour on old browsers and mobile, let me know if it fixes your bug on IE. Anyway, I can't really debug on it since I don't have Windows. I close the issue. If other people encounter the same bug I will reopen.

**Closed by soywod** 2021-03-14 22:40 UTC
Labels: bug, help wanted
