### ISSUE TITLE
Pasting code on IOS Chrome not working from Message

### ISSUE THREAD

**Issue by mattiLeBlanc** [soywod/react-pin-field#63] opened 2022-07-05 06:04 UTC
> I am still having this issue on IOS Chrome and IOS webview with version 3.0.15.
> 
> https://user-images.githubusercontent.com/5285035/177253115-62a179c0-7b67-4d8f-b1da-04d5468fe899.mp4
> 
> Also used the example, same issue on Chrome on IOS: 
> 
> https://user-images.githubusercontent.com/5285035/177255061-0db84e5f-d824-4a59-8856-55b95e7ae8d1.mp4

The problem mentioned in the issues below is still actual in version 3.0.15. I have posted videos in both stories.

We have a react app using the latest version and it doesn't allow quick paste from IOS Message into the box, it only fills the first box with one number.

https://github.com/soywod/react-pin-field/issues/52

**Comment by soywod** [comment] 2022-07-05 07:06
Hi, thank you for the video it helps me to understand the issue. It looks like when you "paste" the code only the first is added, right? My main problem is I do not have an iOS, I cannot debug this properly.

From your videos, where does the code comes from? A SMS? If it is not a sensitive one, could you share it?

**Comment by mattiLeBlanc** [comment] 2022-07-05 08:26
Hi,
Yes the code is coming from an OTP sms. It only pastes in the first box.

**Comment by soywod** [comment] 2022-07-05 08:41
I was able to reproduce again with this same setup https://github.com/soywod/react-pin-field/issues/28#issuecomment-803283478. Only the first char is added. I remember to have fixed this in a previous release, it looks like a regression. I will check this ASAP!

**Comment by mattiLeBlanc** [comment] 2022-07-05 10:23
@soywod if you could release a new version, I am happy to test it for you. It would spare me moving to another library.

**Comment by soywod** [comment] 2022-07-05 19:05
The bug should be fixed, I just released the `v3.0.16`. Feel free to reopen if the issue persist!

**Comment by soywod** [comment] 2022-07-06 07:09
Damn it, I was really sure this time xD when I use the autocomplete mode it does spread, I do not know how to reproduce this behaviour on Android. I will investigate and let you know!

**Comment by mattiLeBlanc** [comment] 2022-07-06 12:32
I hope you can fix the spread, so we can keep using your library. Thanks for your help!

**Comment by soywod** [comment] 2022-07-06 12:38
I will, I just need to find some free time to do it :wink:

**Comment by mattiLeBlanc** [comment] 2022-07-07 23:27
Any update on this issue?

**Comment by soywod** [comment] 2022-07-08 07:20
As I said, I need free time to do it. This is an open source project, I'm not paid for it (unfortunately). If your really need this bug to be fixed quickly according to your deadlines I encourage you either to send a pull request (you know how to reproduce the bug, so it should be easy for your to debug and potentially fix it) or to support me with a donation (which would allow me to allocate time for it).

**Comment by mattiLeBlanc** [comment] 2022-07-09 03:13
Okay, I will move to a different library then because I had a look at the code and I have no context of how it works. I couldn't find the event triggering on an ios OTP code auto complete.
I have no time to debug your code unfortunately.

**Comment by trntv** [comment] 2022-11-21 09:21
> #28 (comment)

Hi, it's easily reproducible on Android. Just send yourself and SMS with the code and try to paste it from the suggestion provided by the keyboard

**Comment by soywod** [comment] 2022-11-21 11:47
I tried on 2 Android phones and I get no suggestion coming from SMS unfortunately :disappointed: so I still cannot reproduce this bug

**Comment by ssijak** [comment] 2023-02-02 14:29
@soywod The issue is that OTP pasting from the phone keyboard (suggested value coming from SMS) does not trigger onPaste event. It is actually typing the code. But an additional issue is that onKeyDown key is `Unknown`, so I am not sure how to properly adjust your code taking that into account.

You can test this by having pin input with `autoComplete="one-time-code"` prop. And then open the page with the pin input on screen, and send SMS message to that phone which mention code explicitly, like : `Your OTP code is: 1234`

**Comment by soywod** [comment] 2023-02-09 20:51
> You can test this by having pin input with `autoComplete="one-time-code"` prop.

This definitely helped me. I also needed to download a keyboard like Gboard to see OTP being proposed (finally). But I still cannot reproduce the issue: the code is pasted correctly :slightly_frowning_face: 

I added `autoComplete="one-time-code"` on the first pin field of the [demo website](https://soywod.github.io/react-pin-field/), feel free to try again. I'm closing the issue since I cannot reproduce since a long time. If someone is able to reproduce, please reopen this issue and give as much information as possible (lib version, OS, browser etc).

**Comment by soywod** [comment] 2023-02-22 13:31
> I believe this issue is strictly connected to this answer:
> https://stackoverflow.com/a/73757650

I am not sure, because the OTP paste works on Android, it looks like an
iOS specific issue.

> I will try to test it by myself when I find some free time.

Could be so great, because I do not have any iOS at home which prevents
me to debug the issue. Let me know!

**Comment by ssijak** [comment] 2023-02-22 13:37
In my app, in the end, I implemented PIN input like only 1 input field, with mono-spaced numbers inside it and large letter spacing and drew fake boxes behind it to give the impression it has X number of digit inputs. It works like a charm with very minimal JS hacking and special cases and it being just one input and not having this focus and input switch shenanigans it works in all scenarios of typing, pasting, auto-complete, etc.

**Comment by soywod** [comment] 2023-02-23 10:11
> In my app, in the end, I implemented PIN input like only 1 input
> field, with mono-spaced numbers inside it and large letter spacing and
> drew fake boxes behind it to give the impression it has X number of
> digit inputs.

It is a very good idea! It is true that you get rid of all the problems
we encounter now. I will experiment with this idea and see how it
behaves compared to the existing implementation. Thank you!

**Comment by benmotyka** [comment] 2023-03-30 17:54
hi @mattiLeBlanc do you have any simple way to have the code on iOS device keyboard, beside sending an actual SMS?

**Comment by mattiLeBlanc** [comment] 2023-03-31 02:46
@benmotyka Do you mean 'have the code' to simulate receiving it and pasting it in the boxes? Not sure how to simulate inputting the code via the IOS keyboard, perhaps a quick google will give you some suggestions? Sorry for not being helpful.

**Closed** 2023-09-09 22:33 UTC
Labels: bug
